version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    command: sleep infinity

    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: bulgogi
      POSTGRES_USER: bulgogi
      POSTGRES_DB: bulgogi

volumes:
  postgres-data:
