name: cd

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: dotoleeoak
          password: ${{ secrets.CR_PAT }}

      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/osamhack2021/military-in:latest
